import { Link } from "@tanstack/react-router";

import { ProviderBadge } from "../components/common/ProviderBadge";
import { SpotIcon } from "../components/icons/SpotIcon";
import { useAppStatus } from "../hooks/useAppStatus";

export function SettingsPage() {
  const status = useAppStatus();

  return <div className="page-stack settings-page"><section className="page-intro"><div><span className="eyebrow">SETTINGS</span><h1>Make it <em>yours.</em></h1><p>Local storage, source connections, and the shape of the player live here.</p></div><span className="version-label">SpotDIY v{status.data?.version ?? "0.1.0"}</span></section><section className="settings-section"><div className="settings-section-heading"><span className="eyebrow">SOURCE CONNECTIONS</span><p>Optional online sources augment your local library. Spotify provides catalog metadata only.</p></div><div className="settings-source-list">{(status.data?.providers ?? []).map((provider) => <div className="settings-source-row" key={provider.kind}><ProviderBadge kind={provider.kind} /><div className="settings-source-copy"><strong>{provider.label}</strong><span>{provider.detail}</span></div><span className={`source-connection-status ${provider.configured ? "connected" : "not-connected"}`}>{provider.configured ? "Connected" : "Not connected"}</span>{provider.kind === "spotify" && !provider.configured ? <button className="button button-small" disabled title="Spotify credentials are wired in the provider integration slice" type="button">Set up source</button> : null}</div>)}</div></section><section className="settings-section"><div className="settings-section-heading"><span className="eyebrow">STORAGE</span><p>SpotDIY keeps application data local. Music remains in the folders you select.</p></div><div className="storage-grid"><div className="storage-card storage-card-active"><div><SpotIcon name="library" size={21} /><span className="storage-card-label">Standard mode</span></div><strong>Windows LocalAppData</strong><p>Recommended for a normal installation.</p><span className="storage-card-state">CURRENT MODE</span></div><div className="storage-card"><div><SpotIcon name="folder" size={21} /><span className="storage-card-label">Portable mode</span></div><strong>Folder-contained data</strong><p>Keep database, covers, lyrics, and cache beside SpotDIY.exe.</p><button className="text-link" disabled title="Portable mode is implemented in the storage slice" type="button">Configure mode <SpotIcon name="arrow" size={14} /></button></div></div></section><section className="settings-footer"><Link className="text-link" to="/library">Open local library <SpotIcon name="arrow" size={14} /></Link><span><span className="status-dot status-dot-active" /> No telemetry by default</span></section></div>;
}
